### PR TITLE
Replaced use of DjsUtil.delayFor

### PR DESCRIPTION
**Pull request by optimisticside**
`delayFor` is not a function of discord.js's `Util` library.

### CODE REVIEW

**Comment by DevYukine** [comment]
Hey, thanks for this PR, can you just import setTimeout without renaming it to delayFor and just change the name where the function is called? i think thats more intuitive :)

otherwise LGTM

**Comment by optimisticside** [comment]
`setTimeout` is already a global function, and would cause confusion. I could call the function `wait` or use it through the library by doing something like `Timers.setTimeout`.

**Comment by DevYukine** [comment]
calling it wait sounds fine to me 👍

**Comment by optimisticside** [comment]
I realized there's already a function in `Util` called `sleep` which does the same thing, so I'll just use that.

**Pull request merged**
